AWSTemplateFormatVersion: '2010-09-09'
Description: A set of Glue workflows for a study

Parameters:

  AppName:
    Type: String
    Description: App whose data this pipeline infrastructure processes

  StudyName:
    Type: String
    Description: Study name, used to name workflows

  SourceBucketName:
    Type: String

  JsonBucketName:
    Type: String

  JsonPrefix:
    Type: String
    Default: raw_json

  ParquetBucketName:
    Type: String

  ParquetPrefix:
    Type: String
    Default: parquet

  DatabaseName:
    Type: String

Resources:

  S3ToJsonWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      DefaultRunProperties:
        app_name: !Ref AppName
        study_name: !Ref StudyName
        source_bucket: !Ref SourceBucketName
        json_bucket: !Ref JsonBucketName
        json_prefix: !Ref JsonPrefix
      Description: >-
        Workflow that breaks apart an archive and stores individual files in S3
      Name: !Sub ${AppName}-${StudyName}-S3ToJsonWorkflow

  JsonToParquetWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      DefaultRunProperties:
        app_name: !Ref AppName
        study_name: !Ref StudyName
        database: !Ref DatabaseName
        json_bucket: !Ref JsonBucketName
        json_prefix: !Sub ${StudyName}/${JsonPrefix}
        parquet_bucket: !Ref ParquetBucketName
        parquet_prefix: !Sub ${StudyName}/${ParquetPrefix}
      Description: Workflow for converting json to parquet
      Name: !Sub ${AppName}-${StudyName}-JsonToParquetWorkflow

Outputs:

  S3ToJsonWorkflowName:
    Value: !Ref S3ToJsonWorkflow
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-S3ToJsonWorkflowName

  JsonToParquetWorkflowName:
    Value: !Ref JsonToParquetWorkflow
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-JsonToParquetWorkflowName
